name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: development
  EMAILS: "mokshitjain18@gmail.com"
  TEST_IMAGE: mokshitjain18/drcode-regression-test-runner:latest

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run regression tests
        run: |
          docker run \
            -e NODE_ENV=${{ env.NODE_ENV }} \
            -e EMAILS=${{ env.EMAILS }} \
            --name drcode-regression-test-runner \
            ${{ env.TEST_IMAGE }}
        continue-on-error: true

      - name: Check container logs
        if: always()
        run: |
          docker logs drcode-regression-test-runner

      - name: Cleanup container
        if: always()
        run: |
          docker rm -f drcode-regression-test-runner || true
