name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: development
  PROJECT_ID: 905
  EMAILS: "mokshitjain18@gmail.com"
  TEST_IMAGE: mokshitjain18/drcode-regression-test-runner:v1

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Start drcode regression test runner
        run: |
          docker run -d -p 3000:3000 --name drcode-regression-test-runner ${{ env.IMAGE_NAME }}