name: CI/CD Pipeline

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_ENV: development
  EMAILS: "mokshitjain18@gmail.com"
  TEST_IMAGE: mokshitjain18/drcode-regression-test-runner:latest
  PROJECT_ID: 905
  PORT: 3000
  LOCAL_HOST: host.docker.internal
  PREFIX: ""

jobs:
  build-and-run-test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: |
          nohup npm run start > app.log 2>&1 &
          sleep 10  # Give the server time to start up
          cat app.log  # Display the logs to verify server started

      - name: Run regression tests and start LocalTunnel
        run: |
          docker run \
            -e NODE_ENV=${{ env.NODE_ENV }} \
            -e EMAILS=${{ env.EMAILS }} \
            -e PROJECT_ID=${{ env.PROJECT_ID }} \
            -e PORT=${{ env.PORT }} \
            -e LOCAL_HOST=${{ env.LOCAL_HOST }} \
            -e PREFIX=${{ env.PREFIX }} \
            --name drcode-regression-test-runner \
            ${{ env.TEST_IMAGE }}
        # continue-on-error: true

      - name: Check container logs
        if: always()
        run: docker logs drcode-regression-test-runner

      - name: Cleanup containers
        if: always()
        run: |
          docker rm -f drcode-regression-test-runner || true

      - name: Check application logs
        if: always()
        run: cat app.log
